language: node_js
node_js:
- '10'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/test.js"
after_success:
- publish-if-needed
env:
  global:
  - secure: mxffRZB3rpnlsdUaZNYY+3WzeOsEOoiHEhnQXGJG4VZqqKN9jBErj0lhK+zqvtz+EI72F+kUzbExxZw8FLewbnYvSBZN4gOEs8nC0uGwtvGNhzm/4D1i8nY1r7O2Q39jqciVaasj06qPnMXuItkdrf0mEzi6NzFYeqYA2oZsyOm7w56r1Xn6a1nMuh4L1ovKREqKE/5T6SZf2J3+vesnmVG4S+oyWUZjOhkxiIL72bGRzQ/E2kTaSHGvapVoBGY/BMDOEsmj/Wy+4X7+3KI07eL0NsXL/su3UW+v29CN3jrKNv+QDKC/inEr1IA1ry7UoEueaq6mAPC00tuZPbbt7V2NhnduVs5dAB4SB1rTtIsNo9lXIbXeA+KQd5H7K6+u9Q6HGxddYR3O1/ybfo0dJF6HXAciCVlbVFx1mIfEMzdFKehHhWmOPpeStbaws687ca+I3pzn7WdlNkhFInQ4nTXkcZ9vC3Z13sm6CtCchzbaJkqRXHa8PnDnieMPdDXV5AbhtwwcDELd+8K8oJYiKjmX8g83HG5kmbjM9WfbbmkEd/IoJmp66JC4sqrCPRWAIMDSgT20+JmBrgITaH2biqvDTkosOU+Ebqm2VQkvaaWsLzZ789/0eQDGgmMHUUlAi87eoLPqJSyzz5JEDl2vqWT6/mtPr7yD5ug+Z97+rvk=
