language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "Wj5lMIUIcBJosWqCOKigy2kSUk35qRknqZaQ1FeUb8O87xGQbY8baDc9D+evT9dzLcN1sPX6OEeMc+GckWEXT/asDfn+CdJhP8DLmH+fGX/HUol4EU7fD1bpJmdc8AKz2BwAkEC0OLsWbgVY2nsBcCU2oqGEOcCfJRc+kKobckWZCjfGrTIsqewLGMZs62y7u/uUZw4HLuhm0PLg1vwNhXxwBULL/v1Vn7lVuO2kXZyp2my5WfkN1PxBemVzR1otUTPo+0R7BVZPeSOILNbHwOcFHlWftDA2eEDm61kkWk3zx4iBFiQkHnJ6jQPO2c/6UtbZGRujJn28yaOkPm+UiES+MyqbLJLgUOl9a2+3cNj0DJoVHWvcOy4XThJVJpBuKLnhA6KGB2TyWnOB9ilNfQfrhliy/Slx00TtBELGQYsq+WayCCHKwuGqHCPaHiX+EVsvgQVtP+aCXhnJSL3Sq5P8E32sJsj4cipA2pW/k9bx9IBQJ7fNjNIBby0so/I9sYLuwPcZWa03oy1iaDK5qKPt8sxtCAQ+aLJ7y7lssfA0A7A1Nbbu/UYcHgnPUYHbj9Yz1zGq3jK8NlX7BW/0qS6iHhujk05tiW2ROFxhICYvkLi5NG2xoa3MbH4wSCs5Oe0HKDRVv9qMTmARhDZvjNY4jFm3hm01ttcBEUnyeqo="
