language: node_js
node_js:
- '10'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install jsdoc -g
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/test.js"
after_success:
- publish-if-needed
env:
  global:
  - secure: ZLOnLYNYWzG2vSW6GAcKFvV2eXvubKyOM+shPU8z9ixq/rTqZo9kDBTcSaKLWL3pfLAOwC7YBKWfcAgXKPj5E902FaT/dj+bKL1Ecbu2vYokU/QrB49/C54LtnLd510fHZVG+G7ZUVZCpUbzZGvD1KrdxpUWaIqlqA+TYZumxz1w8D+tf0sa/URrrWy3oj6CfaWP/81XbKLW6WRqBZB1eyF90ijzuX4EkaNF4CPvqbrbXszNOnmj4OSMTzpgrwMg9+FUuPRa0Ooxl3iJDdAJQgQF2b7RVcDH38RhPEVwvcpe+9L9KuNt710CZk6SdrethL9rWrB8pe4BQtMP5Iz8nDZoVKOtxDkoKUq3NKybKZ2OM86Bi1z4WJeE0OpTrqfVi0ojFHH66uTe9kIqUmuPuYX5F1XwstqsRlFuEyrUw73zj8jSad0Xzu27Wz+Vlp09lxN2hRrxJTMrpAYO1ijyod1OGg3odEbt3unaqaQqBbTGICS83UhxNh0e6ma6k4LpxNcudIJr66ck2IPwY4PJ4Jw6dLbNK/0pdtyIuMDf1/JTPS63HhGfp30tETjIhbZiXlLZ5+QqJFBeYWiDSBqg1DWaeaygrqwzcZ6dMkwvgw559GREW5WtqNo+nQpqR7Q0Xa+q0pHy0lBvBr04uVNZoslcU/76+DG0xlCbU5Mb9rY=
  - secure: gCCmAYVbMSHFGln9F9XIU/NK7KlY09Zxy0FCjbzr9E3AVI7ENkuLhpe+0ypNLoOX7Mwb0OEUG+ikXxhT33LyHpN6n5/cD2GBdj42dM0sYKSMGiRcaywRChDeeOlX+SEEuHFKW8twpEuAjes2JGnk3D7/uzkbLB/9XvSxsZ/stl6V/+nDoK80jDB2/d3BwJ8cHZQj2IZdaWqkzGWU91z38vujhA3MefwrmWjEzdwNRqygXabga1Wba7mc0x52ogtjjdHaq2Aock/LX3c0oFJf/4QcQa2ZhkL4Vtr+SCkUSFr+J55pXY3XLad/Nym6pH75GYBXG/HaIdhDVglm5WTQqMiMeqhATREBBG3r6UFFRJ79DEHAlIsJp+P0x7ANWCGcScpV7T1v6RvD4KZMqIfFxLSXI26csYR7INPDlExDTN5pPUWXiUIOQ5ZdDxwAzhOvBeHlljpsk5N1ayiEumgJFq76WvE0MTO/+8HK1ChMU+19bwG8IfLH5pUtibPbmG/VnTzzgoWiaI0sOh2FVbcHIFuekXxhzTzc36tcb/p/VEFdy8OW49kdz791fLcEQVenbF/40UI4xoSgzoqGQo1fnR/jGQYQOfBtHuM1rHkFECPVdPwnZ93I9JumQAN5gta3PDt6pRrY7QXzkE7o73phbVRGByTsQL1H1uXUCD3Aviw=
